### ISSUE TITLE
Specialty Digital Settings Support for 9411 in EtherCAT Chassis

### ISSUE THREAD

**Issue by tarmanan** [ni/niveristand-scan-engine-ethercat-custom-device#165]
**Is your feature request related to a problem? Please describe.**
The EtherCAT custom device supports the 9411 module when used in the EtherCAT chassis, however, it does not provide the full Specialty Digital Settings that are offered when the 9411 module is in the Local Chassis

![image](https://user-images.githubusercontent.com/46938263/109824617-fe1ea000-7c06-11eb-8b6f-07d7108f80c0.png)

**Describe the solution you'd like**
Support for Specialty Digital Settings when used in the EtherCAT chassis.  We use the 9411 module as a Counter on every test fixture project we create - supporting speed sensors, liquid flow meters, and encoders.  Less frequently as a Quadrature, but occasionally.

![image](https://user-images.githubusercontent.com/46938263/109824726-17bfe780-7c07-11eb-81df-3ddf77ef8961.png)

**Describe alternatives you've considered**
We currently use an FPGA that enables use of the 9411 as a Counter in the EtherCAT chassis [attached]
[EtherCAT_FPGA_Freq_VeriStand 2019.zip](https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/files/6076906/EtherCAT_FPGA_Freq_VeriStand.2019.zip)

**Additional context**

**Comment by Karl-G1** [comment]
@tarmanan 
Unfortunately, the answer to this request is similar to #92: the EtherCAT chassis Scan Engine implementation does not include support for Specialty Digital configurations at all. Because the driver does not support it, we cannot expose it in the Custom Device. There's a [KB ](https://knowledge.ni.com/KnowledgeArticleDetails?id=kA00Z0000004AiLSAU&l=en-US)documenting this lack of functionality, and this has not been addressed over the years.

Because of this, your workaround using a custom FPGA bitfile on your EtherCAT chassis is the only viable option to implement this functionality.
