### ISSUE TITLE
Deployment of custom errors

### ISSUE THREAD

**Issue by Sarci1** [ni/niveristand-scan-engine-ethercat-custom-device#57]
**Describe the bug**
The package does not appear to properly install the custom errors file that is generated for this custom device.

**To Reproduce**
1. Install the package 
2. Go to <Program Files>\National Instruments\Shared\Errors
3. Note that the ...errors.txt file is not present

**Expected behavior**
I would expect this file to be here in order for VeriStand to correctly interpret the error.

**Comment by rtzoeller** [comment]
The shared nature of `<Program Files>\National Instruments\Shared\Errors` makes it difficult to install the errors file directly to this location using our current build pipeline. Since this path is not versioned, custom devices for multiple years of VeriStand will attempt to install the same file, which leads to issues when uninstalling. One solution would be to create a shared error provider package, that all year versions could require. This is not supported by the current custom device build pipeline, unfortunately.

Fortunately, built applications also look in `<Program Files>\National Instruments\Shared\LabVIEW Run-Time\<LabVIEW version>\errors\`. Since this is year-specific, the above issue will not apply.

I'll move forward on prototyping the described fix.
