### ISSUE TITLE
Remove Version property from main page, since the displayed version doesn't reflect the release version

### ISSUE THREAD

**Issue by Sarci1** [ni/niveristand-scan-engine-ethercat-custom-device#70]
This can be confusing for the installer, not being able to correlate between GitHub and what is installed.

**Comment by rtzoeller** [comment]
Hi @Sarci1,

I agree that this can be a point of confusion, however at this time we are unlikely to change it. The version in XML is primarily used as an internal version number (e.g. for mutation), and isn't really intended to be exposed directly to the user in the normal case.

Using the release version in the XML poses technical challenges. Specifically, it would tie our custom device mutation logic to our release process, which is a coupling that we would like to avoid.

---

Since the custom device is consumed through NIPM, I am proposing removing the version property from the custom device main page. 
![image](https://user-images.githubusercontent.com/573497/72754013-45c1a400-3b8c-11ea-9a8b-15e6e1cbaea0.png)

This would encourage customers to check the version in NIPM, which should prevent them from seeing this issue. Does this seem like an acceptable workaround @Sarci1?

**Comment by Sarci1** [comment]
I agree with this logic!
