### ISSUE TITLE
Scan Engine and Ethercat custom device interface in veristand

### ISSUE THREAD

**Issue by anike94** [ni/niveristand-scan-engine-ethercat-custom-device#9]
Hello
I am currently working on a hybrid mode interface with veristand. By going through forums we come to know it requires scan engine and EtherCAT custom device so I downloaded the
  NI VeriStand 2017 with NI-RIO 17.0+ and EtherCAT 17.0+:
   Scan Engine and EtherCAT 2017  
After I downloaded I directly placed the scan engine folder in \Documents\National Instruments\NI VeriStand 2017\Custom Devices \. I am able to add the custom device in veristand (Configuring modules and bit file) but when I try to deploy in Veristand RT it shows an error(Please find the attached image 2 states that VI is not executable), So I try to open the source code it shows an error(Please find the attached image 3 states that LabVIEW error code 3)
Can anyone please guide me to know exactly what is the problem and also please share the working custom device for 2017 version
I am using LabVIEW and veristand 2017 and cRIO-9076 also I will attach all the softwares installed
![image2](https://user-images.githubusercontent.com/45994641/50215682-c15d8a00-03a9-11e9-8784-b12f2b23fcb7.PNG)
![host pc sofwares](https://user-images.githubusercontent.com/45994641/50216009-a4758680-03aa-11e9-897a-17b0f4cddb3e.PNG)
![host pc softwares1](https://user-images.githubusercontent.com/45994641/50216026-accdc180-03aa-11e9-8bff-f6f6f447de9f.PNG)
![rt software](https://user-images.githubusercontent.com/45994641/50216038-b35c3900-03aa-11e9-889d-58914cf1b8ca.PNG)
![rt software 1](https://user-images.githubusercontent.com/45994641/50216043-b9eab080-03aa-11e9-9667-506aa3c584a6.PNG)
![image 3](https://user-images.githubusercontent.com/45994641/50216095-e1da1400-03aa-11e9-8af7-3952af0af369.PNG)

**Comment by tannerblair** [comment]
@christinesparks, can you offer any insight here?

**Comment by christinesparks** [comment]
So a couple things to note here:

1. The cRIO chassis you are trying to use is an older chassis that only has a single ethernet port which makes it incompatible with EtherCAT (which you already knew). This is also a controller with limited memory and processor capability and you may struggle to get VeriStand running on it successfully even if we do resolve this issue.
2. You are getting the LV error "error code 3: could not load front panel" because you are trying to open VIs in the build LLBs. Opening them will likely not resolve the deployment issue you are facing, but if you wanted to do so you'd want to download the source from this GitHub page instead of using the built LLBs.

I believe the source introduced a necessary dependency on the ethercat driver at some point during its development. I am planning on testing this theory and then will file an additional issue so that NI can investigate the issue. There is a small chance of this being fixed immediately so if you are under tight timelines I would suggest either getting a hold of a different cRIO (I'd recommend the 906x or 903x for VeriStand) or by using exclusively FPGA I/O and utilizing the native FPGA support or looking at the FPGA Custom Device (https://github.com/NIVeriStandAdd-Ons/FPGA-Custom-Device).

**Comment by anike94** [comment]
Hello
Thank you for your reply. Is it possible for you to share the working Scan Engine and EthercaT custom device that you have tested for LabVIEW and Veristand 2017 Version, because I  downloaded from online may be it get corrupted. So it will be great help if you share the custom device
Thank You

**Comment by rtzoeller** [comment]
@anike94 were you able to work with NI support to resolve or work around the issues you were experiencing? Can this issue be closed?

I will file another issue to track the behavior that using the custom device with exclusively local modules still requires the EtherCAT driver to be installed.

**Comment by rtzoeller** [comment]
I've captured the underlying bug [here](https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/issues/26), closing this.
