### ISSUE TITLE
 SEECD 2020.2 on PharLap cannot run ECAT 9145 in hybrid mode with FPGA bitfile

### ISSUE THREAD

**Issue by keprt** [ni/niveristand-scan-engine-ethercat-custom-device#91]
**Describe the bug**
ECAT 9145 hybrid mode with FPGA bitfile fails with error 1031 (VI Reference type does not match) on Compare ECAT FPGA Wrapper.vi

**To Reproduce**
1. Open the attached TestProject_EtherCAT_FPGA.nivsproj
2. Upload the FPGA bitfile (test has 9474 in slot 8, however the bug could be seen even without model) 
3. Deploy the system definition

**Expected behavior**
Successful deployement 

**Screenshots**
see below

**Desktop (please complete the following information):**
 - OS:  Pharlap
 - Version: VS 2020 R2

**Additional context**
Reproduction case and screenshots attached

[003 ScanEngineEthercatTest.zip](https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/files/5194316/003.ScanEngineEthercatTest.zip)
![Annotation 2020-09-09 115125](https://user-images.githubusercontent.com/8394296/92584365-d7a12d00-f293-11ea-962a-49d8d16e9976.jpg)
![Annotation 2020-09-09 115140](https://user-images.githubusercontent.com/8394296/92584367-d96af080-f293-11ea-8255-977b59c07605.jpg)

**Comment by Karl-G1** [comment]
### Problem summary
@keprt Thanks for the thorough write-up. I did some digging this morning, and this has been broken for all 20.0+ releases. It stems from @fmussi's change in https://github.com/ni/niveristand-scan-engine-ethercat-custom-device/commit/01bc68dcf98633fcce51d09b7e7edbf84884b431. The 'UDP Data Type.ctl' type def was modified and is reference by the FPGA Data.ctl which is used as an input to the asynchronous call in Compare ECAT FPGA.vi. Because the strictly typed VI ref in the Compare ECAT FPGA Wrapper.vi was not updated in that same submission, the asynchronous call errors out.

### Workaround

![image](https://user-images.githubusercontent.com/31290917/92620896-cd2d6600-f288-11ea-9168-779be5a166a2.png)

If you look closely, the existing Call by Reference node has a coercion dot on the FPGA in terminal. Creating a new strictly typed VI ref from the current state of the Compare ECAT FPGA.vi and wiring that to the Open VI Reference call fixes the issue.

### Next steps
I will get a fix submitted to the repo shortly, as well as unit tests around the wrapper VIs and a system test for ECAT FPGA I/O. We will likely patch the v20.3.0 release that just went live so we can quickly get this working for VeriStand 2020+ versions.
@keprt if you need a fix quickly, you can use a dev build with the change for testing.

**Comment by keprt** [comment]
Hi @Karl-G1  thank you for the quick help. The problem is clear. I will let customer to decide if he will wait on 20.3 patch or he wants to do a dev build until that. 
Unit test would be appreciated.
FYI @czokubik

**Comment by JiriVejrazka** [comment]
@Karl-G1 , @keprt : I updated the vi reference, recompiled and I can deploy the project now. I hence do not need to wait for the patch.
Thank you very much!
