### ISSUE TITLE
IEEE 1451, Transducer Electronic Data Sheets [TEDs] Support

### ISSUE THREAD

**Issue by tarmanan** [ni/niveristand-scan-engine-ethercat-custom-device#92]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
TEDs [IEEE 1451] support / detection in the Scan Engine for EtherCAT custom device.  Similar to "Auto-Detect Modules"?

**Describe alternatives you've considered**
Gather information from MAX?

**Additional context**
All new instrumentation purchases by our group require TEDs-compatibility, if available.  

To the best of my knowledge, the Scan Interface does not support TEDs?  What limitations exist to prevent the TEDs functionality?

References:  

+ https://www.ni.com/en-us/support/documentation/supplemental/18/frequently-asked-questions-about-teds-sensors.html
+ https://forums.ni.com/t5/LabVIEW/Does-the-cRIO-scan-engine-support-TEDS/td-p/775178?profile.language=en

**Comment by Karl-G1** [comment]
@tarmanan It is not possible to expose TEDS support in the Scan Engine Custom Device because there is not support for TEDS in the Scan Engine at all. The configuration for TEDS-compatible C Series Modules in Scan Mode do not allow TEDS to be used. It appears that they are only supported in FPGA mode.

The best workaround I can think of would be to use a custom FPGA bitfile for the CompactRIO and C Series Modules in FPGA mode. You can then return the data to VeriStand with User-Defined Variables (UDVs) via the Custom Device.
